export const COMPANY_LOGO_API = 'https://www.logo.dev/api/search';
export const DEFAULT_REVALIDATION = 3600 * 24 * 5; // 5 days

export const MAANG_COMPANIES = [
  "Meta",
  "Apple",
  "Amazon",
  "Netflix",
  "Google",
  "Microsoft"
];

export const TOP_PRODUCT_COMPANIES_INDIA = [
  "Zomato",
  "Flipkart",
  "Paytm",
  "Ola",
  "Swiggy",
  "Myntra",
  "CRED",
  "Razorpay",
  "Zeta",
  "PhonePe"
]

// Non MAANG
export const TOP_PRODUCT_MNCS = [
  "Uber",
  "Spotify",
  "Salesforce",
  "Shopify",
  "Snap",
  "Adobe",
  "Dropbox",
  "Stripe",
  "Airbnb",
  "LinkedIn"
]

export const DATA_STRUCTURES = [
  "Stack",
  "Trie",
  "Ordered Set",
  "Graph",
  "Binary Tree",
  "Queue",
  "Monotonic Queue",
  "Database",
  "Iterator",
  "Matrix",
  "Segment Tree",
  "Binary Indexed Tree",
  "Suffix Array",
  "Linked List",
  "Doubly-Linked List",
  "Tree",
  "Array",
  "String",
  "Hash Table",
  "Heap (Priority Queue)",
  "Binary Search Tree"
];

export const ALGORITHMS = [
  "Memoization",
  "Monotonic Stack",
  "Eulerian Circuit",
  "Hash Function",
  "Shell",
  "Sorting",
  "Bucket Sort",
  "Minimum Spanning Tree",
  "Depth-First Search",
  "Breadth-First Search",
  "Union Find",
  "Shortest Path",
  "Counting Sort",
  "Bit Manipulation",
  "Brainteaser",
  "Number Theory",
  "Reservoir Sampling",
  "Rejection Sampling",
  "Greedy",
  "Topological Sort",
  "Biconnected Component",
  "Randomized",
  "Simulation",
  "Recursion",
  "Counting",
  "Radix Sort",
  "Quickselect",
  "Merge Sort",
  "Prefix Sum",
  "Rolling Hash",
  "Interactive",
  "Binary Search",
  "Design",
  "Line Sweep",
  "Geometry",
  "Combinatorics",
  "Backtracking",
  "Enumeration",
  "Two Pointers",
  "Divide and Conquer",
  "Data Stream",
  "Math",
  "Dynamic Programming",
  "Sliding Window",
  "Game Theory",
  "String Matching",
  "Strongly Connected Component",
  "Concurrency",
  "Bitmask",
  "Probability and Statistics"
];

export const COMPANIES = [
    "AMD",
    "AQR Capital Management",
    "Accenture",
    "Accolite",
    "Acko",
    "Activision",
    "Adobe",
    "Affirm",
    "Agoda",
    "Airbnb",
    "Airbus SE",
    "Airtel",
    "Airwallex",
    "Akamai",
    "Akuna Capital",
    "Alibaba",
    "Altimetrik",
    "Amadeus",
    "Amazon",
    "Amdocs",
    "American Express",
    "Analytics Quotient",
    "Anduril",
    "Aon",
    "Apollo.io",
    "AppDynamics",
    "AppFolio",
    "Apple",
    "Applied Intuition",
    "Arcesium",
    "Arista Networks",
    "Asana",
    "Atlassian",
    "Attentive",
    "Audible",
    "Aurora",
    "Autodesk",
    "Avalara",
    "Avito",
    "Axon",
    "BILL Holdings",
    "BNY Mellon",
    "BP",
    "Baidu",
    "Bank Of America",
    "Barclays",
    "Bentley Systems",
    "BharatPe",
    "BitGo",
    "BlackRock",
    "BlackStone",
    "Blizzard",
    "Block",
    "Bloomberg",
    "Bolt",
    "Booking.com",
    "Bosch",
    "Box",
    "Braze",
    "Brex",
    "Bridgewater Associates",
    "ByteDance",
    "CARS24",
    "CEDCOSS",
    "CME Group",
    "CRED",
    "CTC",
    "CVENT",
    "Cadence",
    "Canonical",
    "Capgemini",
    "Capital One",
    "Careem",
    "Cashfree",
    "Celigo",
    "Chewy",
    "Chime",
    "Circle",
    "Cisco",
    "Citadel",
    "Citigroup",
    "Citrix",
    "Clari",
    "Cleartrip",
    "Cloudera",
    "Cloudflare",
    "Coforge",
    "Cognizant",
    "Cohesity",
    "Coinbase",
    "Comcast",
    "Commvault",
    "Compass",
    "Confluent",
    "ConsultAdd",
    "Coupang",
    "Coursera",
    "Coveo",
    "Credit Karma",
    "Criteo",
    "CrowdStrike",
    "Cruise",
    "CureFit",
    "DE Shaw",
    "DP World",
    "DRW",
    "DXC Technology",
    "Darwinbox",
    "Databricks",
    "Datadog",
    "Dataminr",
    "Delhivery",
    "Deliveroo",
    "Dell",
    "Deloitte",
    "DeltaX",
    "Deutsche Bank",
    "DevRev",
    "Devsinc",
    "Devtron",
    "Directi",
    "Disney",
    "Docusign",
    "DoorDash",
    "Dream11",
    "Dropbox",
    "Druva",
    "Dunzo",
    "Duolingo",
    "EPAM Systems",
    "EY",
    "EarnIn",
    "Edelweiss Group",
    "Electronic Arts",
    "Epic Systems",
    "Expedia",
    "FPT",
    "FactSet",
    "Faire",
    "Fastenal",
    "Fidelity",
    "Fiverr",
    "Flexera",
    "Flexport",
    "Flipkart",
    "Fortinet",
    "Freecharge",
    "FreshWorks",
    "GE Digital",
    "GE Healthcare",
    "GSA Capital",
    "GSN Games",
    "Gameskraft",
    "Garmin",
    "Geico",
    "General Motors",
    "Genpact",
    "GoDaddy",
    "Gojek",
    "Goldman Sachs",
    "Google",
    "Grab",
    "Grammarly",
    "Graviton",
    "Groupon",
    "Groww",
    "Guidewire",
    "Gusto",
    "HCL",
    "HP",
    "HPE",
    "HSBC",
    "Houzz",
    "Huawei",
    "Hubspot",
    "Hudson River Trading",
    "Hulu",
    "IBM",
    "IIT Bombay",
    "IMC",
    "SOTI",
    "Salesforce",
    "Samsara",
    "Samsung",
    "Scale AI",
    "Sentry",
    "ServiceNow",
    "ShareChat",
    "Shopee",
    "Shopify",
    "Siemens",
    "Sigmoid",
    "Slice",
    "Smartsheet",
    "Snap",
    "Snapdeal",
    "Snowflake",
    "SoFi",
    "Societe Generale",
    "Softwire",
    "Sony",
    "SoundHound",
    "Splunk",
    "Spotify",
    "Sprinklr",
    "Squarepoint Capital",
    "Squarespace",
    "StackAdapt",
    "Stackline",
    "Stripe",
    "Sumo Logic",
    "Swiggy",
    "Synopsys",
    "Tanium",
    "Target",
    "Tech Mahindra",
    "Tejas Networks",
    "Tekion",
    "Tencent",
    "Teradata",
    "Tesco",
    "Tesla",
    "Texas Instruments",
    "The Trade Desk",
    "Thomson Reuters",
    "ThoughtWorks",
    "ThousandEyes",
    "Tiger Analytics",
    "TikTok",
    "Tinder",
    "Tinkoff",
    "Toast",
    "Toptal",
    "Trilogy",
    "Tripadvisor",
    "Turo",
    "Turvo",
    "Vimeo",
    "Virtu Financial",
    "Tower Research Capital",
    "Trexquant",
    "TuSimple",
    "Turing",
    "Twilio",
    "Twitch",
    "Two Sigma",
    "UBS",
    "UKG",
    "USAA",
    "Uber",
    "UiPath",
    "Unity",
    "Upstart",
    "Urban Company",
    "VK",
    "VMware",
    "Veeva Systems",
    "Verily",
    "Veritas",
    "Verkada",
    "Virtusa",
    "Visa",
    "Walmart Labs",
    "Warnermedia",
    "WatchGuard",
    "Wayfair",
    "Waymo",
    "WeRide",
    "Wealthfront",
    "Wells Fargo",
    "Western Digital",
    "Whatnot",
    "WinZO",
    "Wipro",
    "Wise",
    "Wish",
    "Wissen Technology",
    "Wix",
    "Workday",
    "Works Applications",
    "WorldQuant",
    "X",
    "Yahoo",
    "Yandex",
    "Yelp",
    "Yext",
    "ZS Associates",
    "ZScaler",
    "Zalando",
    "Zendesk",
    "Zenefits",
    "Zepto",
    "Zeta",
    "Zillow",
    "ZipRecruiter",
    "Zluri",
    "Zoho",
    "Zomato",
    "Zoom",
    "Zoox",
    "Zopsmart",
    "Zynga",
    "Athenahealth",
    "Blinkit",
    "Carwale",
    "Ciena",
    "EBay",
    "Fourkites",
    "Instabase",
    "Jio",
    "Josh Technology",
    "Opentext",
    "Oyo",
    "Peak6",
    "Persistent Systems",
    "Razorpay",
    "Redbus",
    "Smartnews",
    "Tcs",
    "Thoughtspot",
    "Zeta Suite"
];
