export const COMPANY_LOGO_API = 'https://www.logo.dev/api/search';
export const DEFAULT_REVALIDATION = 3600 * 24 * 5; // 5 days

export const DATA_STRUCTURES = [
  "Stack",
  "Trie",
  "Ordered Set",
  "Graph",
  "Binary Tree",
  "Queue",
  "Monotonic Queue",
  "Database",
  "Iterator",
  "Matrix",
  "Segment Tree",
  "Binary Indexed Tree",
  "Suffix Array",
  "Linked List",
  "Doubly-Linked List",
  "Tree",
  "Array",
  "String",
  "Hash Table",
  "Heap (Priority Queue)",
  "Binary Search Tree"
];

export const ALGORITHMS = [
  "Memoization",
  "Monotonic Stack",
  "Eulerian Circuit",
  "Hash Function",
  "Shell",
  "Sorting",
  "Bucket Sort",
  "Minimum Spanning Tree",
  "Depth-First Search",
  "Breadth-First Search",
  "Union Find",
  "Shortest Path",
  "Counting Sort",
  "Bit Manipulation",
  "Brainteaser",
  "Number Theory",
  "Reservoir Sampling",
  "Rejection Sampling",
  "Greedy",
  "Topological Sort",
  "Biconnected Component",
  "Randomized",
  "Simulation",
  "Recursion",
  "Counting",
  "Radix Sort",
  "Quickselect",
  "Merge Sort",
  "Prefix Sum",
  "Rolling Hash",
  "Interactive",
  "Binary Search",
  "Design",
  "Line Sweep",
  "Geometry",
  "Combinatorics",
  "Backtracking",
  "Enumeration",
  "Two Pointers",
  "Divide and Conquer",
  "Data Stream",
  "Math",
  "Dynamic Programming",
  "Sliding Window",
  "Game Theory",
  "String Matching",
  "Strongly Connected Component",
  "Concurrency",
  "Bitmask",
  "Probability and Statistics"
];