export const BASE_URL =
  process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";

export const COMPANY_LOGO_API = 'https://www.logo.dev/api/search';
export const LOGO_DEV_TOKEN = process.env.NEXT_PUBLIC_LOGO_DEV_TOKEN ?? 'pk_eQPbG0_jSyqQCL92PlOJHw';
export const DEFAULT_REVALIDATION = 86400; // 1 day

export const SHEET_OWNER_LOGO_SRC: Record<string, string> = {
  "neetcode": "https://z47zz7i0co.ufs.sh/f/bMhmuI0QmiRzhaTNSjub5uXrLm8EJjBGM4PN7ZQpVDOsgyTe",
  "tech interview handbook": "https://z47zz7i0co.ufs.sh/f/bMhmuI0QmiRz8UZeBzKskcTQ9NJVa4z2GF1OARDSE3j7PUlM",
  "leetcode": `https://img.logo.dev/leetcode.com?token=${LOGO_DEV_TOKEN}`,
  "striver": "https://z47zz7i0co.ufs.sh/f/bMhmuI0QmiRzgkXJGF0zLQN5a9KoE4WqsIdBF0DCUycTueiX"
}

export const SHEETS_GROUPED_BY_TOPIC = ['blind-75', 'leetcode-75', 'leetcode-top-interview-150', 'leetcode-top-100-liked', 'neetcode-150', 'neetcode-250', 'striver-sde-sheet', 'striver-a2z-dsa', 'striver-79'];

export const DIFFICULTIES = ['Easy', 'Medium', 'Hard'];

export const MAANG_COMPANIES = [
  "Meta",
  "Apple",
  "Amazon",
  "Netflix",
  "Google",
  "Microsoft"
];

export const TOP_PRODUCT_COMPANIES_INDIA = [
  "Zomato",
  "Flipkart",
  "Paytm",
  "Ola",
  "Swiggy",
  "Myntra",
  "Cred",
  "Razorpay",
  "Zeta",
  "Phonepe"
]

// Non MAANG
export const TOP_PRODUCT_MNCS = [
  "Uber",
  "Spotify",
  "Salesforce",
  "Shopify",
  "Snap",
  "Adobe",
  "Dropbox",
  "Stripe",
  "Airbnb",
  "Linkedin"
]

export const DATA_STRUCTURES = [
  "Stack",
  "Trie",
  "Ordered Set",
  "Graph",
  "Binary Tree",
  "Queue",
  "Monotonic Queue",
  "Database",
  "Iterator",
  "Matrix",
  "Segment Tree",
  "Binary Indexed Tree",
  "Suffix Array",
  "Linked List",
  "Doubly-Linked List",
  "Tree",
  "Array",
  "String",
  "Hash Table",
  "Heap (Priority Queue)",
  "Binary Search Tree"
];

export const ALGORITHMS = [
  "Memoization",
  "Monotonic Stack",
  "Eulerian Circuit",
  "Hash Function",
  "Shell",
  "Sorting",
  "Bucket Sort",
  "Minimum Spanning Tree",
  "Depth-First Search",
  "Breadth-First Search",
  "Union Find",
  "Shortest Path",
  "Counting Sort",
  "Bit Manipulation",
  "Brainteaser",
  "Number Theory",
  "Reservoir Sampling",
  "Rejection Sampling",
  "Greedy",
  "Topological Sort",
  "Biconnected Component",
  "Randomized",
  "Simulation",
  "Recursion",
  "Counting",
  "Radix Sort",
  "Quickselect",
  "Merge Sort",
  "Prefix Sum",
  "Rolling Hash",
  "Interactive",
  "Binary Search",
  "Design",
  "Line Sweep",
  "Geometry",
  "Combinatorics",
  "Backtracking",
  "Enumeration",
  "Two Pointers",
  "Divide and Conquer",
  "Data Stream",
  "Math",
  "Dynamic Programming",
  "Sliding Window",
  "Game Theory",
  "String Matching",
  "Strongly Connected Component",
  "Concurrency",
  "Bitmask",
  "Probability and Statistics"
];

export const COMPANIES = {
    "1kosmos": "1kosmos.com",
    "6sense": "6sense.com",
    "Accelya": "accelya.com",
    "Accenture": "accenture.com",
    "Accolite": "accolite.com",
    "Acko": "acko.com",
    "Acorns": "acorns.com",
    "Activision": "activision.com",
    "Adobe": "adobe.com",
    "Adp": "adp.com",
    "Aetion": "aetion.com",
    "Affinity": "affinity.co",
    "Affirm": "affirm.com",
    "Agoda": "agoda.com",
    "Airbnb": "airbnb.com",
    "Airbus": "airbus.com",
    "Airtel": "airtel.in",
    "Airwallex": "airwallex.com",
    "Akamai": "akamai.com",
    "Akuna Capital": "akunacapital.com",
    "Alibaba": "alibaba.com",
    "Allincall": "allincall.in",
    "Alphonso": "alphonso.tv",
    "Alten": "alten.com",
    "Altimetrik": "altimetrik.com",
    "Amadeus": "amadeus.com",
    "Amazon": "amazon.com",
    "Amd": "amd.com",
    "Amdocs": "amdocs.com",
    "American Airlines": "americanairlines.com",
    "American Express": "americanexpress.com",
    "Amplitude": "amplitude.com",
    "Analytics Quotient": "aqinsights.com",
    "Andela": "andela.com",
    "Anduril": "anduril.com",
    "Anthropic": "anthropic.com",
    "Anyscale": "anyscale.com",
    "Aon": "aon.com",
    "Apolloio": "apollo.io",
    "Appdynamics": "appdynamics.com",
    "Appfolio": "appfolio.com",
    "Apple": "apple.com",
    "Applied Intuition": "appliedintuition.com",
    "Applovin": "applovin.com",
    "Aqr Capital Management Llc": "aqr.com",
    "Arcesium": "arcesium.com",
    "Argo Ai": "argo.ai",
    "Arista Networks": "arista.com",
    "Asana": "asana.com",
    "Ascend": "ascend.io",
    "At T": "att.com",
    "Athenahealth": "athenahealth.com",
    "Atlassian": "atlassian.com",
    "Attentive": "attentive.com",
    "Audible": "audible.com",
    "Auriga": "auriga.com",
    "Aurora": "aurora.tech",
    "Autodesk": "autodesk.com",
    "Avalara": "avalara.com",
    "Avito": "avito.ru",
    "Axis Bank": "axisbank.com",
    "Axon": "axon.com",
    "Baidu": "baidu.com",
    "Bank Of America": "bankofamerica.com",
    "Barclays": "barclays.com",
    "Bcg": "bcg.com",
    "Bending Spoons": "bendingspoons.com",
    "Bitgo": "bitgo.com",
    "Blackbuck": "blackbuck.com",
    "Blackrock": "blackrock.com",
    "Blackstone": "blackstone.com",
    "Blend": "blend.com",
    "Blinkit": "blinkit.com",
    "Bloomberg": "bloomberg.com",
    "Bloomreach": "bloomreach.com",
    "Blue Origin": "blueorigin.com",
    "Bnp Paribas": "bnpparibas.com",
    "Bny Mellon": "bny.com",
    "Boeing": "boeing.com",
    "Bolt": "bolt.com",
    "Bookingcom": "booking.com",
    "Box": "box.com",
    "Bp": "bp.com",
    "Braze": "braze.com",
    "Bridgewater Associates": "bridgewater.com",
    "Brillio": "brillio.com",
    "Broadcom": "broadcom.com",
    "Browserstack": "browserstack.com",
    "Bt Group": "bt.com",
    "Buyhatke": "buyhatke.com",
    "Bytedance": "bytedance.com",
    "C3 Ai": "c3.ai",
    "Cadence": "cadence.com",
    "Canonical": "canonical.com",
    "Canva": "canva.com",
    "Capgemini": "capgemini.com",
    "Capital One": "capitalone.com",
    "Careem": "careem.com",
    "Cars24": "cars24.com",
    "Carwale": "carwale.com",
    "Cashfree": "cashfree.com",
    "Caterpillar": "caterpillar.com",
    "Cerner": "cerner.com",
    "Chalo": "chalo.com",
    "Chargebee": "chargebee.com",
    "Checkpoint": "checkpoint.com",
    "Chewy": "chewy.com",
    "Chime": "chime.com",
    "Chubb": "chubb.com",
    "Ciena": "ciena.com",
    "Circle": "circle.com",
    "Cisco": "cisco.com",
    "Citadel": "citadel.com",
    "Citi": "citi.com",
    "Citrix": "citrix.com",
    "Clari": "clari.com",
    "Cleartrip": "cleartrip.com",
    "Clevertap": "clevertap.com",
    "Cloudera": "cloudera.com",
    "Cloudflare": "cloudflare.com",
    "Clutter": "clutter.com",
    "Cme Group": "cmegroup.com",
    "Cockroach Labs": "cockroachlabs.com",
    "Code Studio": "codingninjas.com",
    "Cognizant": "cognizant.com",
    "Cohesity": "cohesity.com",
    "Coinbase": "coinbase.com",
    "Coindcx": "coindcx.com",
    "Coinswitch Kuber": "coinswitch.co",
    "Comcast": "comcast.com",
    "Commvault": "commvault.com",
    "Compass": "compass.com",
    "Confluent": "confluent.io",
    "Couchbase": "couchbase.com",
    "Coupa": "coupa.com",
    "Coupang": "coupang.com",
    "Coursera": "coursera.org",
    "Coveo": "coveo.com",
    "Cred": "cred.club",
    "Credit Karma": "creditkarma.com",
    "Criteo": "criteo.com",
    "Crowdstrike": "crowdstrike.com",
    "Cruise Automation": "getcruise.com",
    "Ctc": "ctc.com",
    "Curefit": "cult.fit",
    "Cvent": "cvent.com",
    "Cyntexa": "cyntexa.com",
    "Cyware": "cyware.com",
    "Dailyhunt": "dailyhunt.in",
    "Darwinbox": "darwinbox.com",
    "Dassault Systemes": "dassault-systemes.com",
    "Dataart": "dataart.com",
    "Databricks": "databricks.com",
    "Datadog": "datadoghq.com",
    "Dataminr": "dataminr.com",
    "De Shaw": "deshaw.com",
    "Deepmind": "deepmind.com",
    "Delhivery": "delhivery.com",
    "Deliveroo": "deliveroo.co.uk",
    "Dell": "dell.com",
    "Deloitte": "deloitte.com",
    "Deltax": "deltax.com",
    "Deutsche Bank": "db.com",
    "Devrev": "devrev.ai",
    "Dialpad": "dialpad.com",
    "Didi": "didiglobal.com",
    "Directi": "directi.com",
    "Discord": "discord.com",
    "Discovery": "discovery.com",
    "Disney": "disney.com",
    "Dji": "dji.com",
    "Docusign": "docusign.com",
    "Doordash": "doordash.com",
    "Dp World": "dpworld.com",
    "Drawbridge": "drawbridge.com",
    "Dream11": "dream11.com",
    "Dropbox": "dropbox.com",
    "Druva": "druva.com",
    "Drw": "drw.com",
    "Dtcc": "dtcc.com",
    "Dunzo": "dunzo.com",
    "Duolingo": "duolingo.com",
    "Earnin": "earnin.com",
    "Ebay": "ebay.com",
    "Edelweiss": "edelweissfin.com",
    "Electronic Arts": "ea.com",
    "Elitmus": "elitmus.com",
    "Epam Systems": "epam.com",
    "Epic Games": "epicgames.com",
    "Epic Systems": "epic.com",
    "Epifi": "epifi.com",
    "Equinix": "equinix.com",
    "Ericsson": "ericsson.com",
    "Etsy": "etsy.com",
    "Expedia": "expedia.com",
    "Ey": "ey.com",
    "F5 Networks": "f5.com",
    "Factset": "factset.com",
    "Factwise": "factwise.io",
    "Faire": "faire.com",
    "Fallible": "fallible.co",
    "Fanatics": "fanatics.com",
    "Fast": "fast.co",
    "Fastenal": "fastenal.com",
    "Fico": "fico.com",
    "Fidelity": "fidelity.com",
    "Fidessa": "fidessa.com",
    "Figma": "figma.com",
    "Fiverr": "fiverr.com",
    "Fivetran": "fivetran.com",
    "Flatiron Health": "flatironhealth.com",
    "Fleetx": "fleetx.io",
    "Flexera": "flexera.com",
    "Flexport": "flexport.com",
    "Flipkart": "flipkart.com",
    "Ford": "ford.com",
    "Fortinet": "fortinet.com",
    "Forusall": "forusall.com",
    "Fourkites": "fourkites.com",
    "Fpt": "fpt.com.vn",
    "Fractal Analytics": "fractal.ai",
    "Freecharge": "freecharge.in",
    "Freshworks": "freshworks.com",
    "Fynd": "fynd.com",
    "Gainsight": "gainsight.com",
    "Gameskraft": "gameskraft.com",
    "Garena": "garena.com",
    "Garmin": "garmin.com",
    "Gartner": "gartner.com",
    "Ge Digital": "ge.com",
    "Ge Healthcare": "gehealthcare.com",
    "Geico": "geico.com",
    "General Electric": "ge.com",
    "General Motors": "gm.com",
    "Genpact": "genpact.com",
    "Gilt Groupe": "gilt.com",
    "Github": "github.com",
    "Glassdoor": "glassdoor.com",
    "Globallogic": "globallogic.com",
    "Globant": "globant.com",
    "Glovo": "glovoapp.com",
    "Godaddy": "godaddy.com",
    "Gojek": "gojek.com",
    "Goldman Sachs": "goldmansachs.com",
    "Google": "google.com",
    "Gopuff": "gopuff.com",
    "Goto": "goto.com",
    "Grab": "grab.com",
    "Grammarly": "grammarly.com",
    "Graviton": "gravitonresearch.com",
    "Groupon": "groupon.com",
    "Groww": "groww.in",
    "Grubhub": "grubhub.com",
    "Gsa Capital": "gsacapital.com",
    "Gsn Games": "gsngames.com",
    "Guidewire": "guidewire.com",
    "Gusto": "gusto.com",
    "Harness": "harness.io",
    "Hashedin": "hashedin.com",
    "Hbo": "hbo.com",
    "Hcl": "hcltech.com",
    "Helix": "helix.com",
    "Hertz": "hertz.com",
    "Highspot": "highspot.com",
    "Hilabs": "hilabs.com",
    "Hive": "hive.com",
    "Honey": "joinhoney.com",
    "Honeywell": "honeywell.com",
    "Hopper": "hopper.com",
    "Hotstar": "hotstar.com",
    "Houzz": "houzz.com",
    "Hp": "hp.com",
    "Hpe": "hpe.com",
    "Hrt": "hudsonrivertrading.com",
    "Hsbc": "hsbc.com",
    "Htc": "htc.com",
    "Huawei": "huawei.com",
    "Hubspot": "hubspot.com",
    "Hulu": "hulu.com",
    "Ibm": "ibm.com",
    "Iit Bombay": "iitb.ac.in",
    "Imc": "imc.com",
    "Impact Analytics": "impactanalytics.co",
    "Increff": "increff.com",
    "Indeed": "indeed.com",
    "Info Edge": "infoedge.in",
    "Informatica": "informatica.com",
    "Infosys": "infosys.com",
    "Inmobi": "inmobi.com",
    "Innovaccer": "innovaccer.com",
    "Instabase": "instabase.com",
    "Instacart": "instacart.com",
    "Intel": "intel.com",
    "Interactive Brokers": "interactivebrokers.com",
    "Intercom": "intercom.com",
    "Intuit": "intuit.com",
    "Ivp": "ivp.in",
    "Ixigo": "ixigo.com",
    "Ixl": "ixl.com",
    "Jane Street": "janestreet.com",
    "Jd": "jd.com",
    "Jeavio": "jeavio.com",
    "Jetbrains": "jetbrains.com",
    "Jingchi": "weride.ai",
    "Jio": "jio.com",
    "Josh Technology": "joshtechnologygroup.com",
    "Jpmorgan": "jpmorgan.com",
    "Jtg": "joshtechnologygroup.com",
    "Jump Trading": "jumptrading.com",
    "Junglee Games": "jungleegames.com",
    "Juspay": "juspay.io",
    "Justworks": "justworks.com",
    "Kakao": "kakaocorp.com",
    "Karat": "karat.com",
    "Keeptruckin": "gomotive.com",
    "Kickdrum": "kickdrumtech.com",
    "Kla": "kla.com",
    "Kla Tencor": "kla.com",
    "Kotak Mahindra Bank": "kotak.com",
    "Kpit": "kpit.com",
    "Kpmg": "kpmg.com",
    "Lacework": "lacework.com",
    "Larsen Toubro": "larsentoubro.com",
    "Leap Motion": "ultraleap.com",
    "Lendingkart": "lendingkart.com",
    "Lenskart": "lenskart.com",
    "Lg Electronics": "lg.com",
    "Liberty Mutual": "libertymutual.com",
    "Liftoff": "liftoff.io",
    "Lime": "li.me",
    "Line": "linecorp.com",
    "Linkedin": "linkedin.com",
    "Liveramp": "liveramp.com",
    "Livspace": "livspace.com",
    "Lowe": "lowes.com",
    "Lti": "lntinfotech.com",
    "Lucid": "lucidmotors.com",
    "Luxoft": "luxoft.com",
    "Lyft": "lyft.com",
    "Machine Zone": "mz.com",
    "Machinezone": "mz.com",
    "Maersk": "maersk.com",
    "Makemytrip": "makemytrip.com",
    "Mapbox": "mapbox.com",
    "Maq Software": "maqsoftware.com",
    "Marqeta": "marqeta.com",
    "Mastercard": "mastercard.com",
    "Mathworks": "mathworks.com",
    "Mcafee": "mcafee.com",
    "Mcdonalds": "mcdonalds.com",
    "Mckinsey": "mckinsey.com",
    "Medianet": "media.net",
    "Meesho": "meesho.com",
    "Meituan": "meituan.com",
    "Mercari": "mercari.com",
    "Meta": "meta.com",
    "Micro1": "micro1.ai",
    "Microsoft": "microsoft.com",
    "Microstrategy": "microstrategy.com",
    "Millennium": "mlp.com",
    "Mindtickle": "mindtickle.com",
    "Mindtree": "ltimindtree.com",
    "Mishipay": "mishipay.com",
    "Mitsogo": "mitsogo.com",
    "Mixpanel": "mixpanel.com",
    "Mobileye": "mobileye.com",
    "Mobisy": "mobisy.com",
    "Moengage": "moengage.com",
    "Moloco": "moloco.com",
    "Moneylion": "moneylion.com",
    "Mongodb": "mongodb.com",
    "Morgan Stanley": "morganstanley.com",
    "Moveworks": "moveworks.com",
    "Msci": "msci.com",
    "Murex": "murex.com",
    "Mykaarma": "mykaarma.com",
    "Myntra": "myntra.com",
    "Nagarro": "nagarro.com",
    "Nasdaq": "nasdaq.com",
    "National Instruments": "ni.com",
    "National Payments Corporation India": "npci.org.in",
    "Natwest": "natwest.com",
    "Navan": "navan.com",
    "Naver": "naver.com",
    "Navi": "navi.com",
    "Ncr": "ncr.com",
    "Nerdwallet": "nerdwallet.com",
    "Netapp": "netapp.com",
    "Netcracker Technology": "netcracker.com",
    "Netease": "netease.com",
    "Netflix": "netflix.com",
    "Netskope": "netskope.com",
    "Netsuite": "netsuite.com",
    "Newsbreak": "newsbreak.com",
    "Nextdoor": "nextdoor.com",
    "Nextjump": "nextjump.com",
    "Nference": "nference.com",
    "Niantic": "niantic.com",
    "Nielsen": "nielsen.com",
    "Nike": "nike.com",
    "Nokia": "nokia.com",
    "Noon": "noon.com",
    "Nordstrom": "nordstrom.com",
    "Notion": "notion.so",
    "Npci": "npci.org.in",
    "Nuro": "nuro.ai",
    "Nutanix": "nutanix.com",
    "Nvidia": "nvidia.com",
    "Nykaa": "nykaa.com",
    "Observeai": "observe.ai",
    "Odoo": "odoo.com",
    "Okta": "okta.com",
    "Okx": "okx.com",
    "Olx": "olx.com",
    "Openai": "openai.com",
    "Opentext": "opentext.com",
    "Oppo": "oppo.com",
    "Optiver": "optiver.com",
    "Optum": "optum.com",
    "Oracle": "oracle.com",
    "Oscar Health": "hioscar.com",
    "Otterai": "otter.ai",
    "Oyo": "oyorooms.com",
    "Ozon": "ozon.ru",
    "Palantir Technologies": "palantir.com",
    "Palo Alto Networks": "paloaltonetworks.com",
    "Park": "park.io",
    "Patreon": "patreon.com",
    "Paycom": "paycom.com",
    "Paypal": "paypal.com",
    "Paypay": "paypay.ne.jp",
    "Paytm": "paytm.com",
    "Payu": "payu.in",
    "Peak6": "peak6.com",
    "Pega": "pega.com",
    "Peloton": "onepeloton.com",
    "Persistent Systems": "persistent.com",
    "Philips": "philips.com",
    "Phonepe": "phonepe.com",
    "Pickrr": "pickrr.com",
    "Pinterest": "pinterest.com",
    "Plaid": "plaid.com",
    "Playsimple": "playsimple.in",
    "Pocket Gems": "pocketgems.com",
    "Point72": "point72.com",
    "Polar": "polar.com",
    "Ponyai": "pony.ai",
    "Pornhub": "pornhub.com",
    "Porter": "porter.in",
    "Poshmark": "poshmark.com",
    "Postman": "postman.com",
    "Postmates": "postmates.com",
    "Poynt": "poynt.com",
    "Practo": "practo.com",
    "Publicis Sapient": "publicissapient.com",
    "Pubmatic": "pubmatic.com",
    "Pure": "pure.com",
    "Pure Storage": "purestorage.com",
    "Purplle": "purplle.com",
    "Pwc": "pwc.com",
    "Qualcomm": "qualcomm.com",
    "Qualtrics": "qualtrics.com",
    "Qualys": "qualys.com",
    "Quantcast": "quantcast.com",
    "Quantiphi": "quantiphi.com",
    "Quince": "quince.com",
    "Quora": "quora.com",
    "Rackspace": "rackspace.com",
    "Radius": "radius.com",
    "Rakuten": "rakuten.com",
    "Rally Health": "rallyhealth.com",
    "Ramp": "ramp.com",
    "Razorpay": "razorpay.com",
    "Rbc": "rbc.com",
    "Redbus": "redbus.in",
    "Reddit": "reddit.com",
    "Redfin": "redfin.com",
    "Remitly": "remitly.com",
    "Retailmenot": "retailmenot.com",
    "Revolut": "revolut.com",
    "Riot Games": "riotgames.com",
    "Ripple": "ripple.com",
    "Rippling": "rippling.com",
    "Rivian": "rivian.com",
    "Robinhood": "robinhood.com",
    "Roblox": "roblox.com",
    "Rokt": "rokt.com",
    "Roku": "roku.com",
    "Rubrik": "rubrik.com",
    "Salesforce": "salesforce.com",
    "Sambanova": "sambanova.ai",
    "Samsara": "samsara.com",
    "Samsung": "samsung.com",
    "Sap": "sap.com",
    "Scale Ai": "scale.com",
    "Scaler": "scaler.com",
    "Schlumberger": "slb.com",
    "Schneider Electric": "se.com",
    "Schrodinger": "schrodinger.com",
    "Sentry": "sentry.io",
    "Servicenow": "servicenow.com",
    "Sharechat": "sharechat.com",
    "Shift Technology": "shift-technology.com",
    "Shipsy": "shipsy.io",
    "Shopee": "shopee.com",
    "Shopify": "shopify.com",
    "Siemens": "siemens.com",
    "Sig": "sig.com",
    "Sigmoid": "sigmoid.com",
    "Singlestore": "singlestore.com",
    "Sixt": "sixt.com",
    "Slice": "sliceit.com",
    "Smartnews": "smartnews.com",
    "Smartsheet": "smartsheet.com",
    "Snapchat": "snap.com",
    "Snapdeal": "snapdeal.com",
    "Snowflake": "snowflake.com",
    "Societe Generale": "societegenerale.com",
    "Sofi": "sofi.com",
    "Softwire": "softwire.com",
    "Sonatus": "sonatus.com",
    "Sony": "sony.com",
    "Soti": "soti.net",
    "Soundhound": "soundhound.com",
    "Spacex": "spacex.com",
    "Spinny": "spinny.com",
    "Splunk": "splunk.com",
    "Spotify": "spotify.com",
    "Sprinklr": "sprinklr.com",
    "Square": "squareup.com",
    "Squarepoint Capital": "squarepoint-capital.com",
    "Squarespace": "squarespace.com",
    "Stackadapt": "stackadapt.com",
    "Stackline": "stackline.com",
    "Starbucks": "starbucks.com",
    "State Farm": "statefarm.com",
    "Strava": "strava.com",
    "Stripe": "stripe.com",
    "Sumologic": "sumologic.com",
    "Swiggy": "swiggy.com",
    "Syfe": "syfe.com",
    "Symantec": "broadcom.com",
    "Synopsys": "synopsys.com",
    "Ta Digital": "tadigital.com",
    "Tableau": "tableau.com",
    "Tanium": "tanium.com",
    "Target": "target.com",
    "Tcs": "tcs.com",
    "Tech Mahindra": "techmahindra.com",
    "Tekion": "tekion.com",
    "Tencent": "tencent.com",
    "Teradata": "teradata.com",
    "Tesco": "tesco.com",
    "Tesla": "tesla.com",
    "Texas Instruments": "ti.com",
    "The Trade Desk": "thetradedesk.com",
    "Thomson Reuters": "thomsonreuters.com",
    "Thoughtspot": "thoughtspot.com",
    "Thoughtworks": "thoughtworks.com",
    "Thousandeyes": "thousandeyes.com",
    "Thumbtack": "thumbtack.com",
    "Tiaa": "tiaa.org",
    "Tiger Analytics": "tigeranalytics.com",
    "Tiktok": "tiktok.com",
    "Tinder": "tinder.com",
    "Tinkoff": "tinkoff.ru",
    "Toast": "toasttab.com",
    "Tokopedia": "tokopedia.com",
    "Tomtom": "tomtom.com",
    "Toptal": "toptal.com",
    "Tower Research": "tower-research.com",
    "Tracxn": "tracxn.com",
    "Traveloka": "traveloka.com",
    "Trend Micro": "trendmicro.com",
    "Trexquant": "trexquant.com",
    "Trilogy": "trilogy.com",
    "Tripactions": "navan.com",
    "Tripadvisor": "tripadvisor.com",
    "Triplebyte": "triplebyte.com",
    "Turing": "turing.com",
    "Turo": "turo.com",
    "Turvo": "turvo.com",
    "Tusimple": "tusimple.com",
    "Twilio": "twilio.com",
    "Twitch": "twitch.tv",
    "Twitter": "x.com",
    "Two Sigma": "twosigma.com",
    "Uber": "uber.com",
    "Ubs": "ubs.com",
    "Udemy": "udemy.com",
    "Uipath": "uipath.com",
    "Ukg": "ukg.com",
    "Unbxd": "unbxd.com",
    "Unity": "unity.com",
    "Unstop": "unstop.com",
    "Upstart": "upstart.com",
    "Urban Company": "urbancompany.com",
    "Ust": "ust.com",
    "Valve": "valvesoftware.com",
    "Veeva": "veeva.com",
    "Verily": "verily.com",
    "Veritas": "veritas.com",
    "Verizon": "verizon.com",
    "Verkada": "verkada.com",
    "Viasat": "viasat.com",
    "Vimeo": "vimeo.com",
    "Virtu": "virtu.com",
    "Virtusa": "virtusa.com",
    "Visa": "visa.com",
    "Vk": "vk.com",
    "Vmware": "vmware.com",
    "Walmart Labs": "walmart.com",
    "Warnermedia": "wbd.com",
    "Watchguard": "watchguard.com",
    "Wayfair": "wayfair.com",
    "Waymo": "waymo.com",
    "Wayve": "wayve.ai",
    "Wealthfront": "wealthfront.com",
    "Wells Fargo": "wellsfargo.com",
    "Weride": "weride.ai",
    "Western Digital": "westerndigital.com",
    "Whatfix": "whatfix.com",
    "Whatnot": "whatnot.com",
    "Winzo": "winzogames.com",
    "Wipro": "wipro.com",
    "Wise": "wise.com",
    "Wish": "wish.com",
    "Wissen": "wissen.com",
    "Wix": "wix.com",
    "Workday": "workday.com",
    "Works Applications": "worksap.com",
    "Worldquant": "worldquant.com",
    "Woven By Toyota": "woven.toyota",
    "Xing": "xing.com",
    "Yahoo": "yahoo.com",
    "Yandex": "yandex.com",
    "Yatra": "yatra.com",
    "Yelp": "yelp.com",
    "Yext": "yext.com",
    "Yugabyte": "yugabyte.com",
    "Zalando": "zalando.com",
    "Zappos": "zappos.com",
    "Zemoso": "zemoso.com",
    "Zendesk": "zendesk.com",
    "Zenefits": "zenefits.com",
    "Zepto": "zepto.com",
    "Zeta": "zeta.tech",
    "Zeta Suite": "zeta.tech",
    "Zillow": "zillow.com",
    "Zip": "ziphq.com",
    "Ziprecruiter": "ziprecruiter.com",
    "Zluri": "zluri.com",
    "Zocdoc": "zocdoc.com",
    "Zoho": "zoho.com",
    "Zomato": "zomato.com",
    "Zoom": "zoom.us",
    "Zoox": "zoox.com",
    "Zopsmart": "zopsmart.com",
    "Zs Associates": "zs.com",
    "Zscaler": "zscaler.com",
    "Zulily": "zulily.com",
    "Zynga": "zynga.com"
};
