export const METADATA = {
    slug: "neetcode-250",
    title: "NeetCode 250",
    description: "An extended list of 250 LeetCode problems building upon NeetCode 150, providing comprehensive coverage of all essential patterns and techniques for coding interviews.",
    ownerName: "NeetCode",
    website: "https://neetcode.io/roadmap"
}

export const PROBLEMS = [
    // Arrays & Hashing
    { order: 1, url: "https://leetcode.com/problems/contains-duplicate/", group: "Arrays & Hashing" },
    { order: 2, url: "https://leetcode.com/problems/valid-anagram/", group: "Arrays & Hashing" },
    { order: 3, url: "https://leetcode.com/problems/two-sum/", group: "Arrays & Hashing" },
    { order: 4, url: "https://leetcode.com/problems/group-anagrams/", group: "Arrays & Hashing" },
    { order: 5, url: "https://leetcode.com/problems/top-k-frequent-elements/", group: "Arrays & Hashing" },
    { order: 6, url: "https://leetcode.com/problems/encode-and-decode-strings/", group: "Arrays & Hashing" },
    { order: 7, url: "https://leetcode.com/problems/product-of-array-except-self/", group: "Arrays & Hashing" },
    { order: 8, url: "https://leetcode.com/problems/valid-sudoku/", group: "Arrays & Hashing" },
    { order: 9, url: "https://leetcode.com/problems/longest-consecutive-sequence/", group: "Arrays & Hashing" },
    { order: 10, url: "https://leetcode.com/problems/sort-colors/", group: "Arrays & Hashing" },
    { order: 11, url: "https://leetcode.com/problems/next-permutation/", group: "Arrays & Hashing" },
    { order: 12, url: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/", group: "Arrays & Hashing" },
    { order: 13, url: "https://leetcode.com/problems/find-all-duplicates-in-an-array/", group: "Arrays & Hashing" },
    { order: 14, url: "https://leetcode.com/problems/first-missing-positive/", group: "Arrays & Hashing" },
    { order: 15, url: "https://leetcode.com/problems/largest-number/", group: "Arrays & Hashing" },
    { order: 16, url: "https://leetcode.com/problems/longest-common-prefix/", group: "Arrays & Hashing" },
    { order: 17, url: "https://leetcode.com/problems/pascals-triangle/", group: "Arrays & Hashing" },
    { order: 18, url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", group: "Arrays & Hashing" },
    { order: 19, url: "https://leetcode.com/problems/remove-element/", group: "Arrays & Hashing" },
    { order: 20, url: "https://leetcode.com/problems/majority-element/", group: "Arrays & Hashing" },

    // Two Pointers
    { order: 21, url: "https://leetcode.com/problems/valid-palindrome/", group: "Two Pointers" },
    { order: 22, url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/", group: "Two Pointers" },
    { order: 23, url: "https://leetcode.com/problems/3sum/", group: "Two Pointers" },
    { order: 24, url: "https://leetcode.com/problems/container-with-most-water/", group: "Two Pointers" },
    { order: 25, url: "https://leetcode.com/problems/trapping-rain-water/", group: "Two Pointers" },
    { order: 26, url: "https://leetcode.com/problems/4sum/", group: "Two Pointers" },
    { order: 27, url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/", group: "Two Pointers" },
    { order: 28, url: "https://leetcode.com/problems/move-zeroes/", group: "Two Pointers" },
    { order: 29, url: "https://leetcode.com/problems/merge-sorted-array/", group: "Two Pointers" },
    { order: 30, url: "https://leetcode.com/problems/rotate-array/", group: "Two Pointers" },

    // Sliding Window
    { order: 31, url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", group: "Sliding Window" },
    { order: 32, url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", group: "Sliding Window" },
    { order: 33, url: "https://leetcode.com/problems/longest-repeating-character-replacement/", group: "Sliding Window" },
    { order: 34, url: "https://leetcode.com/problems/permutation-in-string/", group: "Sliding Window" },
    { order: 35, url: "https://leetcode.com/problems/minimum-window-substring/", group: "Sliding Window" },
    { order: 36, url: "https://leetcode.com/problems/sliding-window-maximum/", group: "Sliding Window" },
    { order: 37, url: "https://leetcode.com/problems/frequency-of-the-most-frequent-element/", group: "Sliding Window" },
    { order: 38, url: "https://leetcode.com/problems/find-all-anagrams-in-a-string/", group: "Sliding Window" },
    { order: 39, url: "https://leetcode.com/problems/minimum-number-of-flips-to-make-the-binary-string-alternating/", group: "Sliding Window" },
    { order: 40, url: "https://leetcode.com/problems/minimum-size-subarray-sum/", group: "Sliding Window" },

    // Stack
    { order: 41, url: "https://leetcode.com/problems/valid-parentheses/", group: "Stack" },
    { order: 42, url: "https://leetcode.com/problems/min-stack/", group: "Stack" },
    { order: 43, url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/", group: "Stack" },
    { order: 44, url: "https://leetcode.com/problems/generate-parentheses/", group: "Stack" },
    { order: 45, url: "https://leetcode.com/problems/daily-temperatures/", group: "Stack" },
    { order: 46, url: "https://leetcode.com/problems/car-fleet/", group: "Stack" },
    { order: 47, url: "https://leetcode.com/problems/largest-rectangle-in-histogram/", group: "Stack" },
    { order: 48, url: "https://leetcode.com/problems/simplify-path/", group: "Stack" },
    { order: 49, url: "https://leetcode.com/problems/removing-stars-from-a-string/", group: "Stack" },
    { order: 50, url: "https://leetcode.com/problems/asteroid-collision/", group: "Stack" },
    { order: 51, url: "https://leetcode.com/problems/decode-string/", group: "Stack" },
    { order: 52, url: "https://leetcode.com/problems/online-stock-span/", group: "Stack" },
    { order: 53, url: "https://leetcode.com/problems/basic-calculator/", group: "Stack" },
    { order: 54, url: "https://leetcode.com/problems/maximal-rectangle/", group: "Stack" },

    // Binary Search
    { order: 55, url: "https://leetcode.com/problems/binary-search/", group: "Binary Search" },
    { order: 56, url: "https://leetcode.com/problems/search-a-2d-matrix/", group: "Binary Search" },
    { order: 57, url: "https://leetcode.com/problems/koko-eating-bananas/", group: "Binary Search" },
    { order: 58, url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", group: "Binary Search" },
    { order: 59, url: "https://leetcode.com/problems/search-in-rotated-sorted-array/", group: "Binary Search" },
    { order: 60, url: "https://leetcode.com/problems/time-based-key-value-store/", group: "Binary Search" },
    { order: 61, url: "https://leetcode.com/problems/median-of-two-sorted-arrays/", group: "Binary Search" },
    { order: 62, url: "https://leetcode.com/problems/guess-number-higher-or-lower/", group: "Binary Search" },
    { order: 63, url: "https://leetcode.com/problems/search-insert-position/", group: "Binary Search" },
    { order: 64, url: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", group: "Binary Search" },
    { order: 65, url: "https://leetcode.com/problems/search-a-2d-matrix-ii/", group: "Binary Search" },
    { order: 66, url: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/", group: "Binary Search" },
    { order: 67, url: "https://leetcode.com/problems/find-peak-element/", group: "Binary Search" },
    { order: 68, url: "https://leetcode.com/problems/successful-pairs-of-spells-and-potions/", group: "Binary Search" },
    { order: 69, url: "https://leetcode.com/problems/split-array-largest-sum/", group: "Binary Search" },

    // Linked List
    { order: 70, url: "https://leetcode.com/problems/reverse-linked-list/", group: "Linked List" },
    { order: 71, url: "https://leetcode.com/problems/merge-two-sorted-lists/", group: "Linked List" },
    { order: 72, url: "https://leetcode.com/problems/reorder-list/", group: "Linked List" },
    { order: 73, url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", group: "Linked List" },
    { order: 74, url: "https://leetcode.com/problems/copy-list-with-random-pointer/", group: "Linked List" },
    { order: 75, url: "https://leetcode.com/problems/add-two-numbers/", group: "Linked List" },
    { order: 76, url: "https://leetcode.com/problems/linked-list-cycle/", group: "Linked List" },
    { order: 77, url: "https://leetcode.com/problems/find-the-duplicate-number/", group: "Linked List" },
    { order: 78, url: "https://leetcode.com/problems/lru-cache/", group: "Linked List" },
    { order: 79, url: "https://leetcode.com/problems/merge-k-sorted-lists/", group: "Linked List" },
    { order: 80, url: "https://leetcode.com/problems/reverse-nodes-in-k-group/", group: "Linked List" },
    { order: 81, url: "https://leetcode.com/problems/linked-list-cycle-ii/", group: "Linked List" },
    { order: 82, url: "https://leetcode.com/problems/palindrome-linked-list/", group: "Linked List" },
    { order: 83, url: "https://leetcode.com/problems/middle-of-the-linked-list/", group: "Linked List" },
    { order: 84, url: "https://leetcode.com/problems/swap-nodes-in-pairs/", group: "Linked List" },
    { order: 85, url: "https://leetcode.com/problems/sort-list/", group: "Linked List" },

    // Trees
    { order: 86, url: "https://leetcode.com/problems/invert-binary-tree/", group: "Trees" },
    { order: 87, url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", group: "Trees" },
    { order: 88, url: "https://leetcode.com/problems/diameter-of-binary-tree/", group: "Trees" },
    { order: 89, url: "https://leetcode.com/problems/balanced-binary-tree/", group: "Trees" },
    { order: 90, url: "https://leetcode.com/problems/same-tree/", group: "Trees" },
    { order: 91, url: "https://leetcode.com/problems/subtree-of-another-tree/", group: "Trees" },
    { order: 92, url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", group: "Trees" },
    { order: 93, url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", group: "Trees" },
    { order: 94, url: "https://leetcode.com/problems/binary-tree-right-side-view/", group: "Trees" },
    { order: 95, url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/", group: "Trees" },
    { order: 96, url: "https://leetcode.com/problems/validate-binary-search-tree/", group: "Trees" },
    { order: 97, url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", group: "Trees" },
    { order: 98, url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", group: "Trees" },
    { order: 99, url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", group: "Trees" },
    { order: 100, url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", group: "Trees" },
    { order: 101, url: "https://leetcode.com/problems/binary-tree-inorder-traversal/", group: "Trees" },
    { order: 102, url: "https://leetcode.com/problems/symmetric-tree/", group: "Trees" },
    { order: 103, url: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/", group: "Trees" },
    { order: 104, url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", group: "Trees" },
    { order: 105, url: "https://leetcode.com/problems/sum-root-to-leaf-numbers/", group: "Trees" },
    { order: 106, url: "https://leetcode.com/problems/path-sum/", group: "Trees" },
    { order: 107, url: "https://leetcode.com/problems/path-sum-ii/", group: "Trees" },
    { order: 108, url: "https://leetcode.com/problems/path-sum-iii/", group: "Trees" },
    { order: 109, url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", group: "Trees" },
    { order: 110, url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", group: "Trees" },

    // Tries
    { order: 111, url: "https://leetcode.com/problems/implement-trie-prefix-tree/", group: "Tries" },
    { order: 112, url: "https://leetcode.com/problems/design-add-and-search-words-data-structure/", group: "Tries" },
    { order: 113, url: "https://leetcode.com/problems/word-search-ii/", group: "Tries" },
    { order: 114, url: "https://leetcode.com/problems/extra-characters-in-a-string/", group: "Tries" },

    // Heap / Priority Queue
    { order: 115, url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/", group: "Heap / Priority Queue" },
    { order: 116, url: "https://leetcode.com/problems/last-stone-weight/", group: "Heap / Priority Queue" },
    { order: 117, url: "https://leetcode.com/problems/k-closest-points-to-origin/", group: "Heap / Priority Queue" },
    { order: 118, url: "https://leetcode.com/problems/kth-largest-element-in-an-array/", group: "Heap / Priority Queue" },
    { order: 119, url: "https://leetcode.com/problems/task-scheduler/", group: "Heap / Priority Queue" },
    { order: 120, url: "https://leetcode.com/problems/design-twitter/", group: "Heap / Priority Queue" },
    { order: 121, url: "https://leetcode.com/problems/find-median-from-data-stream/", group: "Heap / Priority Queue" },
    { order: 122, url: "https://leetcode.com/problems/ipo/", group: "Heap / Priority Queue" },
    { order: 123, url: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/", group: "Heap / Priority Queue" },
    { order: 124, url: "https://leetcode.com/problems/top-k-frequent-words/", group: "Heap / Priority Queue" },
    { order: 125, url: "https://leetcode.com/problems/reorganize-string/", group: "Heap / Priority Queue" },

    // Backtracking
    { order: 126, url: "https://leetcode.com/problems/subsets/", group: "Backtracking" },
    { order: 127, url: "https://leetcode.com/problems/combination-sum/", group: "Backtracking" },
    { order: 128, url: "https://leetcode.com/problems/permutations/", group: "Backtracking" },
    { order: 129, url: "https://leetcode.com/problems/subsets-ii/", group: "Backtracking" },
    { order: 130, url: "https://leetcode.com/problems/combination-sum-ii/", group: "Backtracking" },
    { order: 131, url: "https://leetcode.com/problems/word-search/", group: "Backtracking" },
    { order: 132, url: "https://leetcode.com/problems/palindrome-partitioning/", group: "Backtracking" },
    { order: 133, url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/", group: "Backtracking" },
    { order: 134, url: "https://leetcode.com/problems/n-queens/", group: "Backtracking" },
    { order: 135, url: "https://leetcode.com/problems/combinations/", group: "Backtracking" },
    { order: 136, url: "https://leetcode.com/problems/permutations-ii/", group: "Backtracking" },
    { order: 137, url: "https://leetcode.com/problems/combination-sum-iii/", group: "Backtracking" },
    { order: 138, url: "https://leetcode.com/problems/splitting-a-string-into-descending-consecutive-values/", group: "Backtracking" },

    // Graphs
    { order: 139, url: "https://leetcode.com/problems/number-of-islands/", group: "Graphs" },
    { order: 140, url: "https://leetcode.com/problems/max-area-of-island/", group: "Graphs" },
    { order: 141, url: "https://leetcode.com/problems/clone-graph/", group: "Graphs" },
    { order: 142, url: "https://leetcode.com/problems/walls-and-gates/", group: "Graphs" },
    { order: 143, url: "https://leetcode.com/problems/rotting-oranges/", group: "Graphs" },
    { order: 144, url: "https://leetcode.com/problems/pacific-atlantic-water-flow/", group: "Graphs" },
    { order: 145, url: "https://leetcode.com/problems/surrounded-regions/", group: "Graphs" },
    { order: 146, url: "https://leetcode.com/problems/course-schedule/", group: "Graphs" },
    { order: 147, url: "https://leetcode.com/problems/course-schedule-ii/", group: "Graphs" },
    { order: 148, url: "https://leetcode.com/problems/graph-valid-tree/", group: "Graphs" },
    { order: 149, url: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/", group: "Graphs" },
    { order: 150, url: "https://leetcode.com/problems/redundant-connection/", group: "Graphs" },
    { order: 151, url: "https://leetcode.com/problems/word-ladder/", group: "Graphs" },
    { order: 152, url: "https://leetcode.com/problems/01-matrix/", group: "Graphs" },
    { order: 153, url: "https://leetcode.com/problems/accounts-merge/", group: "Graphs" },
    { order: 154, url: "https://leetcode.com/problems/evaluate-division/", group: "Graphs" },
    { order: 155, url: "https://leetcode.com/problems/snakes-and-ladders/", group: "Graphs" },
    { order: 156, url: "https://leetcode.com/problems/open-the-lock/", group: "Graphs" },
    { order: 157, url: "https://leetcode.com/problems/minimum-genetic-mutation/", group: "Graphs" },
    { order: 158, url: "https://leetcode.com/problems/keys-and-rooms/", group: "Graphs" },
    { order: 159, url: "https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/", group: "Graphs" },

    // Advanced Graphs
    { order: 160, url: "https://leetcode.com/problems/reconstruct-itinerary/", group: "Advanced Graphs" },
    { order: 161, url: "https://leetcode.com/problems/min-cost-to-connect-all-points/", group: "Advanced Graphs" },
    { order: 162, url: "https://leetcode.com/problems/network-delay-time/", group: "Advanced Graphs" },
    { order: 163, url: "https://leetcode.com/problems/swim-in-rising-water/", group: "Advanced Graphs" },
    { order: 164, url: "https://leetcode.com/problems/alien-dictionary/", group: "Advanced Graphs" },
    { order: 165, url: "https://leetcode.com/problems/cheapest-flights-within-k-stops/", group: "Advanced Graphs" },
    { order: 166, url: "https://leetcode.com/problems/path-with-maximum-probability/", group: "Advanced Graphs" },
    { order: 167, url: "https://leetcode.com/problems/path-with-minimum-effort/", group: "Advanced Graphs" },

    // 1-D Dynamic Programming
    { order: 168, url: "https://leetcode.com/problems/climbing-stairs/", group: "1-D Dynamic Programming" },
    { order: 169, url: "https://leetcode.com/problems/min-cost-climbing-stairs/", group: "1-D Dynamic Programming" },
    { order: 170, url: "https://leetcode.com/problems/house-robber/", group: "1-D Dynamic Programming" },
    { order: 171, url: "https://leetcode.com/problems/house-robber-ii/", group: "1-D Dynamic Programming" },
    { order: 172, url: "https://leetcode.com/problems/longest-palindromic-substring/", group: "1-D Dynamic Programming" },
    { order: 173, url: "https://leetcode.com/problems/palindromic-substrings/", group: "1-D Dynamic Programming" },
    { order: 174, url: "https://leetcode.com/problems/decode-ways/", group: "1-D Dynamic Programming" },
    { order: 175, url: "https://leetcode.com/problems/coin-change/", group: "1-D Dynamic Programming" },
    { order: 176, url: "https://leetcode.com/problems/maximum-product-subarray/", group: "1-D Dynamic Programming" },
    { order: 177, url: "https://leetcode.com/problems/word-break/", group: "1-D Dynamic Programming" },
    { order: 178, url: "https://leetcode.com/problems/longest-increasing-subsequence/", group: "1-D Dynamic Programming" },
    { order: 179, url: "https://leetcode.com/problems/partition-equal-subset-sum/", group: "1-D Dynamic Programming" },
    { order: 180, url: "https://leetcode.com/problems/n-th-tribonacci-number/", group: "1-D Dynamic Programming" },
    { order: 181, url: "https://leetcode.com/problems/counting-bits/", group: "1-D Dynamic Programming" },
    { order: 182, url: "https://leetcode.com/problems/delete-and-earn/", group: "1-D Dynamic Programming" },
    { order: 183, url: "https://leetcode.com/problems/integer-break/", group: "1-D Dynamic Programming" },
    { order: 184, url: "https://leetcode.com/problems/maximum-length-of-pair-chain/", group: "1-D Dynamic Programming" },
    { order: 185, url: "https://leetcode.com/problems/number-of-longest-increasing-subsequence/", group: "1-D Dynamic Programming" },
    { order: 186, url: "https://leetcode.com/problems/perfect-squares/", group: "1-D Dynamic Programming" },

    // 2-D Dynamic Programming
    { order: 187, url: "https://leetcode.com/problems/unique-paths/", group: "2-D Dynamic Programming" },
    { order: 188, url: "https://leetcode.com/problems/longest-common-subsequence/", group: "2-D Dynamic Programming" },
    { order: 189, url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/", group: "2-D Dynamic Programming" },
    { order: 190, url: "https://leetcode.com/problems/coin-change-ii/", group: "2-D Dynamic Programming" },
    { order: 191, url: "https://leetcode.com/problems/target-sum/", group: "2-D Dynamic Programming" },
    { order: 192, url: "https://leetcode.com/problems/interleaving-string/", group: "2-D Dynamic Programming" },
    { order: 193, url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/", group: "2-D Dynamic Programming" },
    { order: 194, url: "https://leetcode.com/problems/distinct-subsequences/", group: "2-D Dynamic Programming" },
    { order: 195, url: "https://leetcode.com/problems/edit-distance/", group: "2-D Dynamic Programming" },
    { order: 196, url: "https://leetcode.com/problems/burst-balloons/", group: "2-D Dynamic Programming" },
    { order: 197, url: "https://leetcode.com/problems/regular-expression-matching/", group: "2-D Dynamic Programming" },
    { order: 198, url: "https://leetcode.com/problems/unique-paths-ii/", group: "2-D Dynamic Programming" },
    { order: 199, url: "https://leetcode.com/problems/minimum-path-sum/", group: "2-D Dynamic Programming" },
    { order: 200, url: "https://leetcode.com/problems/maximal-square/", group: "2-D Dynamic Programming" },
    { order: 201, url: "https://leetcode.com/problems/triangle/", group: "2-D Dynamic Programming" },
    { order: 202, url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/", group: "2-D Dynamic Programming" },
    { order: 203, url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/", group: "2-D Dynamic Programming" },
    { order: 204, url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/", group: "2-D Dynamic Programming" },
    { order: 205, url: "https://leetcode.com/problems/ones-and-zeroes/", group: "2-D Dynamic Programming" },

    // Greedy
    { order: 206, url: "https://leetcode.com/problems/maximum-subarray/", group: "Greedy" },
    { order: 207, url: "https://leetcode.com/problems/jump-game/", group: "Greedy" },
    { order: 208, url: "https://leetcode.com/problems/jump-game-ii/", group: "Greedy" },
    { order: 209, url: "https://leetcode.com/problems/gas-station/", group: "Greedy" },
    { order: 210, url: "https://leetcode.com/problems/hand-of-straights/", group: "Greedy" },
    { order: 211, url: "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/", group: "Greedy" },
    { order: 212, url: "https://leetcode.com/problems/partition-labels/", group: "Greedy" },
    { order: 213, url: "https://leetcode.com/problems/valid-parenthesis-string/", group: "Greedy" },
    { order: 214, url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/", group: "Greedy" },
    { order: 215, url: "https://leetcode.com/problems/assign-cookies/", group: "Greedy" },
    { order: 216, url: "https://leetcode.com/problems/candy/", group: "Greedy" },
    { order: 217, url: "https://leetcode.com/problems/lemonade-change/", group: "Greedy" },
    { order: 218, url: "https://leetcode.com/problems/maximum-length-of-subarray-with-positive-product/", group: "Greedy" },

    // Intervals
    { order: 219, url: "https://leetcode.com/problems/insert-interval/", group: "Intervals" },
    { order: 220, url: "https://leetcode.com/problems/merge-intervals/", group: "Intervals" },
    { order: 221, url: "https://leetcode.com/problems/non-overlapping-intervals/", group: "Intervals" },
    { order: 222, url: "https://leetcode.com/problems/meeting-rooms/", group: "Intervals" },
    { order: 223, url: "https://leetcode.com/problems/meeting-rooms-ii/", group: "Intervals" },
    { order: 224, url: "https://leetcode.com/problems/minimum-interval-to-include-each-query/", group: "Intervals" },
    { order: 225, url: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/", group: "Intervals" },

    // Math & Geometry
    { order: 226, url: "https://leetcode.com/problems/rotate-image/", group: "Math & Geometry" },
    { order: 227, url: "https://leetcode.com/problems/spiral-matrix/", group: "Math & Geometry" },
    { order: 228, url: "https://leetcode.com/problems/set-matrix-zeroes/", group: "Math & Geometry" },
    { order: 229, url: "https://leetcode.com/problems/happy-number/", group: "Math & Geometry" },
    { order: 230, url: "https://leetcode.com/problems/plus-one/", group: "Math & Geometry" },
    { order: 231, url: "https://leetcode.com/problems/powx-n/", group: "Math & Geometry" },
    { order: 232, url: "https://leetcode.com/problems/multiply-strings/", group: "Math & Geometry" },
    { order: 233, url: "https://leetcode.com/problems/detect-squares/", group: "Math & Geometry" },
    { order: 234, url: "https://leetcode.com/problems/spiral-matrix-ii/", group: "Math & Geometry" },
    { order: 235, url: "https://leetcode.com/problems/roman-to-integer/", group: "Math & Geometry" },
    { order: 236, url: "https://leetcode.com/problems/integer-to-roman/", group: "Math & Geometry" },
    { order: 237, url: "https://leetcode.com/problems/sqrtx/", group: "Math & Geometry" },
    { order: 238, url: "https://leetcode.com/problems/factorial-trailing-zeroes/", group: "Math & Geometry" },

    // Bit Manipulation
    { order: 239, url: "https://leetcode.com/problems/single-number/", group: "Bit Manipulation" },
    { order: 240, url: "https://leetcode.com/problems/number-of-1-bits/", group: "Bit Manipulation" },
    { order: 241, url: "https://leetcode.com/problems/counting-bits/", group: "Bit Manipulation" },
    { order: 242, url: "https://leetcode.com/problems/reverse-bits/", group: "Bit Manipulation" },
    { order: 243, url: "https://leetcode.com/problems/missing-number/", group: "Bit Manipulation" },
    { order: 244, url: "https://leetcode.com/problems/sum-of-two-integers/", group: "Bit Manipulation" },
    { order: 245, url: "https://leetcode.com/problems/reverse-integer/", group: "Bit Manipulation" },
    { order: 246, url: "https://leetcode.com/problems/single-number-ii/", group: "Bit Manipulation" },
    { order: 247, url: "https://leetcode.com/problems/single-number-iii/", group: "Bit Manipulation" },
    { order: 248, url: "https://leetcode.com/problems/add-binary/", group: "Bit Manipulation" },
    { order: 249, url: "https://leetcode.com/problems/bitwise-and-of-numbers-range/", group: "Bit Manipulation" },
    { order: 250, url: "https://leetcode.com/problems/minimum-flips-to-make-a-or-b-equal-to-c/", group: "Bit Manipulation" }
];
